# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: googlefonts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11googlefonts.proto\"\x85\x01\n\x04\x46ont\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05style\x18\x02 \x01(\t\x12\x0e\n\x06weight\x18\x03 \x01(\x02\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\x12\x18\n\x10post_script_name\x18\x05 \x01(\t\x12\x11\n\tfull_name\x18\x06 \x01(\t\x12\x11\n\tcopyright\x18\x07 \x01(\t\"9\n\x04\x41xes\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x11\n\tmin_value\x18\x02 \x01(\x02\x12\x11\n\tmax_value\x18\x03 \x01(\x02\"E\n\x06Source\x12\x16\n\x0erepository_url\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\t\x12\x13\n\x0b\x61rchive_url\x18\x03 \x01(\t\"6\n\x18RegistryDefaultOverrides\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\xf7\x02\n\x08\x46ontInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65signer\x18\x02 \x01(\t\x12\x0f\n\x07license\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x03(\t\x12\x12\n\ndate_added\x18\x05 \x01(\t\x12\x14\n\x05\x66onts\x18\x06 \x03(\x0b\x32\x05.Font\x12\x0f\n\x07subsets\x18\x07 \x03(\t\x12\x13\n\x04\x61xes\x18\x08 \x03(\x0b\x32\x05.Axes\x12\x17\n\x06source\x18\t \x01(\x0b\x32\x07.Source\x12=\n\x1aregistry_default_overrides\x18\n \x03(\x0b\x32\x19.RegistryDefaultOverrides\x12\x0f\n\x07is_noto\x18\x0b \x01(\x08\x12\x11\n\tlanguages\x18\x0c \x03(\t\x12\x18\n\x10primary_language\x18\r \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x0e \x03(\t\x12\x16\n\x0eprimary_script\x18\x0f \x01(\t\x12\x14\n\x0cminisite_url\x18\x10 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'googlefonts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FONT']._serialized_start=22
  _globals['_FONT']._serialized_end=155
  _globals['_AXES']._serialized_start=157
  _globals['_AXES']._serialized_end=214
  _globals['_SOURCE']._serialized_start=216
  _globals['_SOURCE']._serialized_end=285
  _globals['_REGISTRYDEFAULTOVERRIDES']._serialized_start=287
  _globals['_REGISTRYDEFAULTOVERRIDES']._serialized_end=341
  _globals['_FONTINFO']._serialized_start=344
  _globals['_FONTINFO']._serialized_end=719
# @@protoc_insertion_point(module_scope)
